"""add lesson video_url

Revision ID: c601cc6be022
Revises: b3d9a4b56c1c
Create Date: 2026-08-17 15:44:13.828008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c601cc6be022'
down_revision: Union[str, None] = 'b3d9a4b56c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('video_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'video_url')
    # ### end Alembic commands ###
